export const IS_LOADING = 'IS_LOADING';

export const GET_ALL_MOVIES = 'GET_ALL_MOVIES';
export const GET_MOVIE_BY_ID = 'GET_MOVIE_BY_ID';
export const GET_MAKER_BY_ID = 'GET_MAKER_BY_ID';
export const GET_FILTER = 'GET_FILTER';
export const GET_MOVIE_RESULTS = 'GET_MOVIE_RESULTS';

export const GET_REVIEWS_BEFORE_LOGIN = 'GET_REVIEWS_BEFORE_LOGIN';
export const GET_REVIEWS_AFTER_LOGIN = 'GET_REVIEWS_AFTER_LOGIN';
export const GET_REVIEWS_BY_ID = 'GET_REVIEWS_BY_ID';
